# Generated by Django 3.0.8 on 2020-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('enrollment_name', models.CharField(max_length=50)),
            ],
        ),
    ]
