# Generated by Django 3.0.8 on 2020-07-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200729_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('staff_ph_no', models.CharField(max_length=10)),
                ('addr', models.TextField()),
                ('staff_username', models.CharField(blank=True, max_length=200)),
                ('staff_password', models.CharField(blank=True, max_length=200)),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subject')),
            ],
        ),
    ]
