# Generated by Django 3.0.8 on 2020-07-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('student_ph_no', models.CharField(max_length=10)),
                ('addr', models.TextField()),
                ('student_uname', models.CharField(blank=True, max_length=200)),
                ('student_password', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
