# Generated by Django 3.0.8 on 2020-07-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_staff_staff_date_joined'),
        ('home', '0004_student'),
    ]

    operations = [
    ]
