# Generated by Django 3.1.3 on 2020-11-16 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200729_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_date_joined',
            field=models.DateField(default=datetime.datetime(2020, 11, 16, 16, 59, 2, 757066, tzinfo=utc)),
        ),
    ]
